// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg3y8qw0N17Jt5LrqBKXc9hrgssZoWFGo',
    appId: '1:547929824611:web:3b6bedf252fa203c468756',
    messagingSenderId: '547929824611',
    projectId: 'kucits-200f2',
    authDomain: 'kucits-200f2.firebaseapp.com',
    storageBucket: 'kucits-200f2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIfscuf5-C-tHDOUUXjsEVpue87Uks2wU',
    appId: '1:547929824611:android:706034aa4bdae106468756',
    messagingSenderId: '547929824611',
    projectId: 'kucits-200f2',
    storageBucket: 'kucits-200f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWqDqovdxAiudhunZW_FNXcEd4WvTjxuM',
    appId: '1:547929824611:ios:cc948eca845ed682468756',
    messagingSenderId: '547929824611',
    projectId: 'kucits-200f2',
    storageBucket: 'kucits-200f2.firebasestorage.app',
    iosBundleId: 'com.example.kucits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWqDqovdxAiudhunZW_FNXcEd4WvTjxuM',
    appId: '1:547929824611:ios:cc948eca845ed682468756',
    messagingSenderId: '547929824611',
    projectId: 'kucits-200f2',
    storageBucket: 'kucits-200f2.firebasestorage.app',
    iosBundleId: 'com.example.kucits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg3y8qw0N17Jt5LrqBKXc9hrgssZoWFGo',
    appId: '1:547929824611:web:ca8531766324fa9b468756',
    messagingSenderId: '547929824611',
    projectId: 'kucits-200f2',
    authDomain: 'kucits-200f2.firebaseapp.com',
    storageBucket: 'kucits-200f2.firebasestorage.app',
  );

}